testpress/android

app/build.gradle, app/src/main/java/in/testpress/testpress/authenticator/CodeVerificationActivity.java, app/src/main/java/in/testpress/testpress/authenticator/NewUserRegistrationActivity.java, app/src/main/java/in/testpress/testpress/authenticator/TestpressAuthenticatorActivity.java, app/src/main/java/in/testpress/testpress/ui/AttemptFragment.java, app/src/main/java/in/testpress/testpress/ui/AttemptsListActivity.java, app/src/main/java/in/testpress/testpress/ui/ItemListFragment.java, app/src/main/java/in/testpress/testpress/ui/MainActivity.java, app/src/main/java/in/testpress/testpress/ui/ReviewActivity.java, app/src/main/java/in/testpress/testpress/ui/TestpressFragmentActivity.java, app/src/main/res/layout/item_list.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/theme.xml
-material dialog is replaced for native AlertDialog & ProgressDialog
Fixes #24
=> Material Dialog

app/src/main/java/in/testpress/testpress/authenticator/CodeVerificationActivity.java, app/src/main/res/layout/code_verify_activity.xml
-Fixes #28 
-if user abort the app before verify complete & verifying later, at that
time the user have to redirect to login screen if code verified instead
get password in verification layout & automatically login
=> Redirect to login screen if password unavailable

app/src/main/AndroidManifest.xml, app/src/main/java/in/testpress/testpress/authenticator/CodeVerificationActivity.java, app/src/main/java/in/testpress/testpress/authenticator/NewUserRegistrationActivity.java, app/src/main/java/in/testpress/testpress/events/SmsReceivingEvent.java, app/src/main/res/layout/code_verify_activity.xml, app/src/main/res/values/strings.xml
-Fixes #26 
-when user successfully registered, the SmsReceivingEvent & Timer will
started
-if the sms received from TSTPRS, the SmsReceivingEvent read the code
& stop timer & handleCodeVerification begin
-User can press manually verify button to type code manually
-if sms not received from TSTPRS till 30 seconds then the user have
to enter the code
-if user abort the app before verification complete then the user
have to verify again using verify code & have to type username,
password, code manually.
=> Automatically Code receiving Implemented

app/src/main/java/in/testpress/testpress/ui/MainActivity.java, app/src/main/res/values/strings.xml
-Fixes #31
-when user click logout Logging out Progress will show till login screen displays
=> Logging out Progress showing

app/src/main/java/in/testpress/testpress/authenticator/CodeVerificationActivity.java, app/src/main/java/in/testpress/testpress/authenticator/NewUserRegistrationActivity.java, app/src/main/java/in/testpress/testpress/authenticator/TestpressAuthenticatorActivity.java, app/src/main/java/in/testpress/testpress/ui/AttemptFragment.java, app/src/main/java/in/testpress/testpress/ui/AttemptsListFragment.java, app/src/main/java/in/testpress/testpress/ui/ExamActivity.java, app/src/main/java/in/testpress/testpress/ui/ExamsListFragment.java, app/src/main/java/in/testpress/testpress/ui/ItemListFragment.java, app/src/main/java/in/testpress/testpress/ui/ReviewActivity.java, app/src/main/java/in/testpress/testpress/ui/ReviewQuestionsFragment.java, app/src/main/java/in/testpress/testpress/util/InternetConnectivityChecker.java, app/src/main/res/layout/item_list.xml, app/src/main/res/values/strings.xml
-Fixes #34 
-if Internet is unavailable when starting the app it will show
message in emptyText on the container.
-likewise in between using the app if Internet unavailable behavior of
app is handled
=> Internet Unavailable handled

app/src/main/java/in/testpress/testpress/ui/ExamActivity.java, app/src/main/java/in/testpress/testpress/ui/MainActivity.java
-Fixes #24 
-material dialog implemented for update alert
=> Material Dialog Implemented

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/in/testpress/testpress/TestpressModule.java, app/src/main/java/in/testpress/testpress/core/Constants.java, app/src/main/java/in/testpress/testpress/core/ProductService.java, app/src/main/java/in/testpress/testpress/core/ProductsPager.java, app/src/main/java/in/testpress/testpress/core/TestpressService.java, app/src/main/java/in/testpress/testpress/models/Product.java, app/src/main/java/in/testpress/testpress/ui/ItemListFragment.java, app/src/main/java/in/testpress/testpress/ui/PagedItemFragment.java, app/src/main/java/in/testpress/testpress/ui/ProductNativeGridBaseFragment.java, app/src/main/java/in/testpress/testpress/ui/ProductsListActivity.java, app/src/main/res/layout/grid_card_grid_view.xml, app/src/main/res/layout/grid_card_native.xml, app/src/main/res/layout/grid_native_inner_content.xml, app/src/main/res/layout/grid_product_layout.xml, app/src/main/res/layout/grid_product_thumbnail_layout.xml, app/src/main/res/menu/testpress.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
-products list is shown in grid cards
-fixes #37
=> Products list in Gridview

app/src/main/java/in/testpress/testpress/ui/ProductNativeGridBaseFragment.java, app/src/main/res/layout/actionbar_spinner.xml, app/src/main/res/values/strings.xml
-spinner bar is added to filter the category of product
-Fixes #38
=> Product Category Filter

app/src/main/AndroidManifest.xml, app/src/main/java/in/testpress/testpress/TestpressModule.java, app/src/main/java/in/testpress/testpress/core/ProductService.java, app/src/main/java/in/testpress/testpress/core/TestpressService.java, app/src/main/java/in/testpress/testpress/models/Notes.java, app/src/main/java/in/testpress/testpress/models/ProductDetails.java, app/src/main/java/in/testpress/testpress/ui/NotesListAdapter.java, app/src/main/java/in/testpress/testpress/ui/ProductDetailsActivity.java, app/src/main/java/in/testpress/testpress/ui/ProductNativeGridBaseFragment.java, app/src/main/res/layout/available_exams_list_item.xml, app/src/main/res/layout/product_details_layout.xml
-Fixes #39 
-clicking on a product in ProductsList will show the product detail
-ui have to improve in future now to implement functionality temporary
ui is kept
=> Product Details

app/src/main/AndroidManifest.xml, app/src/main/java/in/testpress/testpress/ui/OrderConfirmActivity.java, app/src/main/java/in/testpress/testpress/ui/TestpressFragmentActivity.java, app/src/main/java/in/testpress/testpress/ui/paymentGateway/CreditDebitCardActivity.java, app/src/main/java/in/testpress/testpress/ui/paymentGateway/NetBankingActivity.java, app/src/main/java/in/testpress/testpress/ui/paymentGateway/PaymentModeActivity.java
--if user press the back arrow instead starting new parent activity
onbackpress method will call
--similarly have to make changes in posts & profile when commit to master
=> backArrowPress Handled

app/src/main/java/in/testpress/testpress/events/SmsReceivingEvent.java
Sms regex format is changed to support all institutes names.
=> Modify sms format in sms receiving event

app/src/main/java/in/testpress/testpress/ui/BottomNavBarAdapter.java, app/src/main/java/in/testpress/testpress/ui/DocumentsListActivity.java, app/src/main/java/in/testpress/testpress/ui/MainActivity.java, app/src/main/java/in/testpress/testpress/ui/MainMenuFragment.java, app/src/main/java/in/testpress/testpress/ui/MainMenuGridAdapter.java, app/src/main/java/in/testpress/testpress/ui/OrdersListActivity.java, app/src/main/java/in/testpress/testpress/ui/PostsListActivity.java, app/src/main/java/in/testpress/testpress/util/UIUtils.java, app/src/main/res/layout/menu_grid_item.xml
Changes Done
- Added dynamic field label for the main menu
Reason for the changes
- Previously label titles were fixed
=> Honor institute setting

app/build.gradle, app/src/main/java/in/testpress/testpress/authenticator/RegisterActivity.java, app/src/main/java/in/testpress/testpress/core/Constants.java, app/src/main/java/in/testpress/testpress/core/TestpressService.java, app/src/main/java/in/testpress/testpress/models/InstituteSettings.java, app/src/main/java/in/testpress/testpress/models/InstituteSettingsDao.java, app/src/main/res/layout/login_activity.xml, app/src/main/res/layout/register_activity.xml, testpressdaogenerator/src/main/java/in/testpress/testpress/TestpressDaoGenerator.java
- Add country code picker at the time of registration.
- Changed the login button colour to primary colour.
- Earlier other country users were facing the issue to register the phone number with there country code.
=> Add option to select international phone code in registration activity.

app/src/main/java/in/testpress/testpress/authenticator/LoginActivity.java, app/src/main/res/layout/login_activity.xml, app/src/main/res/values/strings.xml
- Added show/hide for the password field
- Moved resend verification SMS below forgot password
- Verticle centered login screen
- To improve UX and usability
=> Add enhancements for login screen

app/src/main/res/drawable/rounded_border_edittext.xml, app/src/main/res/layout-xlarge/activity_reset_password.xml, app/src/main/res/layout-xlarge/login_activity.xml, app/src/main/res/layout-xlarge/register_activity.xml, app/src/main/res/layout/activity_reset_password.xml, app/src/main/res/layout/login_activity.xml, app/src/main/res/layout/register_activity.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/styles.xml
- Changed input styles for the login screen, forgot password and signup screen
- To make the app UI cleaner
=> Add UI enhancements

app/src/main/AndroidManifest.xml, app/src/main/java/in/testpress/testpress/authenticator/LoginActivity.java, app/src/main/java/in/testpress/testpress/authenticator/RegisterActivity.java, app/src/main/java/in/testpress/testpress/authenticator/ResetPasswordActivity.java, app/src/main/res/drawable/primary_rounded_button.xml, app/src/main/res/drawable/rounded_border_edittext.xml, app/src/main/res/layout-xlarge/activity_reset_password.xml, app/src/main/res/layout-xlarge/login_activity.xml, app/src/main/res/layout-xlarge/register_activity.xml, app/src/main/res/layout/activity_reset_password.xml, app/src/main/res/layout/login_activity.xml, app/src/main/res/layout/register_activity.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
- Add border-radius to button.
- Add empty data validation for login and register screen.
- Set status bar color.
- To improve UX
=> Improve app UX

app/src/main/java/in/testpress/testpress/ui/MainActivity.java, app/src/main/java/in/testpress/testpress/ui/utils/HandleMainMenu.java, app/src/main/res/menu/main_menu.xml
- Hide navigation items which require authentication
- Display Login in navigation drawer if user is unauthenticated
=> Handle navigation drawer for unauthenticated user

app/src/main/java/in/testpress/testpress/ui/adapters/CourseCarouselAdapter.java, app/src/main/res/values/strings.xml
- Displayed notes count, videos count and exams count in course carousel.
=> Display Contents count in course carousel

app/src/main/java/in/testpress/testpress/ui/SplashScreenActivity.java, app/src/main/java/in/testpress/testpress/ui/adapters/DashboardAdapter.java, app/src/main/java/in/testpress/testpress/ui/adapters/OffersCarouselAdapter.java, app/src/main/java/in/testpress/testpress/ui/fragments/DashboardFragment.java, app/src/main/java/in/testpress/testpress/ui/utils/DeeplinkHandler.java, app/src/main/java/in/testpress/testpress/ui/view_holders/OffersCarouselViewHolder.java
- Added deeplink support to dashboard banners such those banner URLs that match will be opened within the app and for others, webview will be displayed.
=> Add deeplink support to banner links

app/src/main/java/in/testpress/testpress/ui/fragments/DashboardFragment.java, app/src/main/res/layout/carousel_placeholder.xml, app/src/main/res/layout/dashboard_view.xml
- Show shimmer loading placeholder when dashboard data is fetched for first time
=> Display shimmer loading placeholder for dashboard

app/src/main/java/in/testpress/testpress/ui/adapters/ContentsCarouselAdapter.java, app/src/main/res/layout/content_carousel_item.xml
- Displayed progress bar videos in resume section of dashboard
=> Display progress bar videos in resume section of dashboard

app/src/main/java/in/testpress/testpress/models/pojo/DashboardResponse.java, app/src/main/java/in/testpress/testpress/ui/adapters/ContentsCarouselAdapter.java
- Removed lorem picsum images for contents carousel
- Displayed images from server
=> Remove lorem picsum images for contents carousel

app/build.gradle, app/src/main/java/in/testpress/testpress/ui/utils/RecyclerViewAttacher.java, app/src/main/java/in/testpress/testpress/ui/view_holders/BaseCarouselViewHolder.java, app/src/main/java/in/testpress/testpress/ui/view_holders/ContentsCarouselViewHolder.java, app/src/main/java/in/testpress/testpress/ui/view_holders/CourseCarouselViewHolder.java, app/src/main/java/in/testpress/testpress/ui/view_holders/PostsCarouselViewHolder.java, app/src/main/res/layout/recycler_view.xml
- Added page indicator for dashboard carousels
- Used third-party package for scrolling indicator
- Since the third party's recycle view scrolling attacher uses androidx which we don't support yet, rewrote the same with support library for us.
=> Add page indicator for dashboard carousels

app/build.gradle, app/src/main/assets/config.json
- Added is_growth_hacks enabled field in config
=> Add is_growth_hacks enabled field in config

app/src/androidTest/java/in/testpress/testpress/fragment/DeleteDownloadedVideosTest.kt, app/src/main/java/in/testpress/testpress/TestpressServiceProvider.java, app/src/main/java/in/testpress/testpress/authenticator/LoginActivity.java, app/src/main/java/in/testpress/testpress/ui/MainActivity.java
- Saving the username in a sharedpref while log out and checking when the user logs in with the same account or not.
- If User log in with another account the videos will be deleted.
=> Delete downloaded videos if user logs out and logs in as another user

app/src/main/java/in/testpress/testpress/authenticator/LoginActivity.java, app/src/main/res/layout/login_activity.xml, app/src/main/res/values/strings.xml
Play store has rejected app since privacy policy is not there. So In sign up page, we can add privacy policy is been added
=> Display Privacy Policy in the signup/login screen

app/src/main/res/drawable/border_rectangle_dark.xml, app/src/main/res/layout/course_carousel_item.xml
- Added a new drawable for black background
- Change the image background drawable to newly generated one.
=> Change course carousel image background to black

app/src/main/java/in/testpress/testpress/ui/DoubtsActivity.kt, app/src/main/java/in/testpress/testpress/ui/WebViewActivity.java
- We are displaying a progress spinner to show that the page is being loaded but it is not looking good.
=> fix: Fix loading jerk in doubts webview

app/src/main/AndroidManifest.xml, app/src/main/java/in/testpress/testpress/ui/WebViewActivity.java
- Audio recording for doubts is not working because of microphone permission error. It is fixed in this commit
=> fix: Fix mic permission in doubts view

app/src/main/java/in/testpress/testpress/ui/MainActivity.java
- Issue is that android-SDK sends results to the main activity, but the main activity does nothing on the activity result, 
- This is fixed by redirecting the user to learn tab and refreshing it on the activity result.
=> fix: Fix goto home button not redirecting user to learn tab

app/src/main/java/in/testpress/testpress/ui/MainActivity.java
=> fix: Show share button in menubar based on institute settings

.github/workflows/build_app.yml, .github/workflows/release_update.yml
- There is some issue with java zulu distribution that is why the Gradle was failing while GitHub actions, that was fixed by using corretto distribution.
=> fix: Fix gradle failure on github actions while generating app files

.github/workflows/build_app.yml, .github/workflows/release_update.yml
=> fix: Prevent printing keyfile URL in Github action

app/src/main/java/in/testpress/testpress/TestpressApplication.java, app/src/main/java/in/testpress/testpress/ui/ForumActivity.java, app/src/main/java/in/testpress/testpress/ui/ForumListAdapter.java, app/src/main/res/layout/forum_details_layout.xml
=> fix: Show voting options on discussion thread based on institute settings

app/src/main/AndroidManifest.xml, app/src/main/java/in/testpress/testpress/ui/MainActivity.java, app/src/main/java/in/testpress/testpress/ui/TermsAndConditionActivity.kt, app/src/main/res/layout/terms_and_condition_activity.xml
-  Added Terms and conditions activity with webview
- Number of Test Cases -  Nil
=> Add registration form in web view activity

app/src/main/java/in/testpress/testpress/ui/TermsAndConditionActivity.kt
-  Added WebViewClient to WebView in TermsAndConditionActivity
-  Added Custom onBackPressed method for webView
- Number of Test Cases -  NIL
=> fix: Not able to view terms and conditions file in webView

app/build.gradle, app/src/main/java/in/testpress/testpress/ui/fragments/PhoneAuthenticationFragment.kt, build.gradle
- 
-
- 
- 
- Number of Test Cases -
=> fix: Fix app build error

app/src/main/java/in/testpress/testpress/TestpressModule.java, app/src/main/java/in/testpress/testpress/authenticator/LoginActivityV2.kt, app/src/main/java/in/testpress/testpress/ui/MainActivity.java, app/src/main/java/in/testpress/testpress/ui/TermsAndConditionActivity.kt, app/src/main/res/menu/logout_terms_and_conditions.xml, app/src/main/res/values/strings.xml
-  Add logout button in action bar
-  Add loading progressbar for web view
- Number of Test Cases -  NIL
=> fix: Not able to logout from TermsAndConditionsActivity

app/src/main/java/in/testpress/testpress/ui/TermsAndConditionActivity.kt, app/src/main/res/layout/terms_and_condition_activity.xml
-  Added network error screen
- Number of Test Cases -  NIL
=> fix: network error screen not visible in TermsAndConditions activity

app/build.gradle, build.gradle, gradle/wrapper/gradle-wrapper.properties, testpressdaogenerator/build.gradle
=> build: Update gradle verion from 4 to 7

app/src/main/java/in/testpress/testpress/ui/fragments/UsernameAuthentication.kt, app/src/main/res/layout-h800dp/phone_login_layout.xml, app/src/main/res/layout-h800dp/username_login_layout.xml, app/src/main/res/layout-hdpi/phone_login_layout.xml, app/src/main/res/layout-hdpi/username_login_layout.xml, app/src/main/res/layout-xhdpi/phone_login_layout.xml, app/src/main/res/layout-xhdpi/username_login_layout.xml, app/src/main/res/layout/phone_login_layout.xml, app/src/main/res/layout/username_login_layout.xml
-  Added Hide soft keyboard function
-  From actionNext to actionDone for the password field in username_login_layout
- From actionNext to actionDone for phoneNumber field in phone_login_layout
=> fix:Not able hide soft keyboard in login screen

app/build.gradle, app/src/main/AndroidManifest.xml, build.gradle, mobilertc/build.gradle
-  android target sdk to 31
-  added zoom SDK version 5.11.0.6883
-  added Bluetooth permission in android manifest file
- update kotlin version to 1.6.0
- Number of Test Cases -  NIL
=> fix: Add zoom support for Version 12

app/build.gradle, app/src/main/assets/config.json, app/src/main/java/in/testpress/testpress/TestpressServiceProvider.java
-  Added toggle support to custom zoom meeting UI
=> Add support to toggle zoom meeting UI

app/build.gradle
- 
-
- 
- 
- Number of Test Cases -
=> build: Use TestpressSDK version 1.4.102

app/src/main/java/in/testpress/testpress/core/Constants.java, app/src/main/java/in/testpress/testpress/ui/MainActivity.java, app/src/main/java/in/testpress/testpress/ui/utils/HandleMainMenu.java, app/src/main/res/drawable/ic_baseline_key_24.xml, app/src/main/res/menu/main_menu.xml, app/src/main/res/values/strings.xml
- This will allow students to access their Proctored Exam option from their mobile.
=> feat: Add Proctored Exam page

mobilertc/build.gradle
- In this commit, we update the Zoom SDK version `5.13.5.11583` to `5.14.11.14322` - [ReleaseNotes](https://devsupport.zoom.us/hc/en-us/sections/9481916215053-Android)
=> enhancement: Update zoom SDK version 5.14.11.14322

app/src/main/java/in/testpress/testpress/ui/fragments/AutoLoginFragment.kt, app/src/main/java/in/testpress/testpress/ui/fragments/EmailVerificationFragment.kt, app/src/main/java/in/testpress/testpress/ui/fragments/ForumAnswerFragment.kt, app/src/main/java/in/testpress/testpress/ui/fragments/OTPVerificationFragment.kt, app/src/main/java/in/testpress/testpress/ui/fragments/PhoneAuthenticationFragment.kt, app/src/main/java/in/testpress/testpress/ui/fragments/PhoneVerificationFragment.kt, build.gradle
- Updated Kotlin version from `1.6.0` to `1.7.0` and corresponding room database version from `2.4.0` to `2.4.3`.
- Added an `else` branch for all when statements due to Kotlin `1.7.0` changes, where `when` statements with `enum`, `sealed`, and `Boolean` subjects are exhaustive by default. More details can be found in the [[Docs](https://kotlinlang.org/docs/compatibility-guide-17.html#make-when-statements-with-enum-sealed-and-boolean-subjects-exhaustive-by-default)] and [[Issue](https://youtrack.jetbrains.com/issue/KT-47709?_gl=1*fa3yyi*_ga*MTE2NDk5ODIwNC4xNzEzNDM5NDk1*_ga_9J976DJZ68*MTcxMzQzOTQ5NC4xLjEuMTcxMzQ0MDU1Ni42MC4wLjA.&_ga=2.73157715.1326330261.1713439495-1164998204.1713439495)].
=> enhancement: Update Kotlin version to 1.7.0

app/src/main/java/in/testpress/testpress/ui/fragments/UsernameAuthentication.kt
- In this commit, we replaced `viewBinding` instead of `kotlin-android-extensions` in UsernameAuthentication
=> enhancement: Use `viewBinding` instead of `kotlin-android-extensions` in UsernameAuthentication

app/src/main/java/in/testpress/testpress/ui/MainActivity.java, app/src/main/java/in/testpress/testpress/ui/utils/HandleMainMenu.java, app/src/main/res/menu/main_menu.xml
- Added new Discussion UI in WebView activity in this commit.
- Moved the Discussion option from the bottom navigation bar to the navigation drawer.
=>  feat: Add new Discussion UI in WebView activity

app/src/main/java/in/testpress/testpress/ui/MainActivity.java, app/src/main/java/in/testpress/testpress/ui/utils/DeeplinkHandler.java
- Added deep link support to open the discussion detail view in WebView in this commit.
- This deep link option will handle both URL clicks and push notifications.
=> feat: Add deep link support to discussion

app/build.gradle, app/src/main/java/in/testpress/testpress/ui/ProfileDetailsActivity.java, app/src/main/java/in/testpress/testpress/ui/utils/DeeplinkHandler.java, app/src/main/java/in/testpress/testpress/ui/utils/HandleMainMenu.java
- In our SDK, we removed SSO login and added JWT token authentication for all WebView functionalities. We are updating our SDK version to `1.4.141`.
- Corresponding changes include adding the base URL for all WebView instances in this commit.
=> fix: Add base url to webview activities

app/build.gradle, app/src/main/java/in/testpress/testpress/repository/ForumAnswerRepository.kt, mobilertc/build.gradle
- In this commit, we update the Zoom SDK version `5.15.12.10095` to `5.16.10.17706`.
- Updated corresponding code changes
=> enhancement: Update zoom SDK version `5.16.10.17706`

app/src/main/res/menu/main_menu.xml
- In this commit, we added grouping options to the navigation slider, allowing for a clearer separation between features and account-related options.
=> enhancement: Add grouping to navigation slider

app/build.gradle, app/src/main/java/in/testpress/testpress/ui/ProfileDetailsActivity.java, app/src/main/java/in/testpress/testpress/ui/utils/DeeplinkHandler.java, app/src/main/java/in/testpress/testpress/ui/utils/HandleMainMenu.java
- Update Testpress SDK version `1.4.162` to `1.4.163`
- Updated corresponding changes.
=> fix: Use Testpress SDK version 1.4.163

app/src/main/java/in/testpress/testpress/ui/MainActivity.java
- This PR introduces a feature enhancement to dynamically control the visibility of the Dashboard based on the DashboardEnabled field received in the institute settings response.
=> enhancement: Show dashboard bases in Institute settings
