- app/src/main/java/in/testpress/testpress/ui/ExamActivity.java
- app/src/main/java/in/testpress/testpress/ui/ReviewActivity.java
After completing the exam / pausing the exam, when you go to history or available screen the screen does not gets refreshed automatically. Instead it shows the old screen. It might look confusing to the user. 
Once the exam has got completed / started the screen needs to get refreshed. 
Test cases: 
Start the exam (Dont end) -> Goto Home menu -> Now launch app. List has to be updated
Start the exam -> Pause the exam ->  Goto History / Available Screen.List has to be updated
Start the exam -> End the exam ->  Goto History / Available Screen.List has to be updated
> Screen Refresh

- app/src/main/java/in/testpress/testpress/ui/AttemptsListFragment.java
- app/src/main/java/in/testpress/testpress/ui/ExamsListFragment.java
- app/src/main/java/in/testpress/testpress/ui/OrdersListFragment.java
- app/src/main/java/in/testpress/testpress/ui/PagedItemFragment.java
- app/src/main/java/in/testpress/testpress/ui/ProductListFragment.java
- app/src/main/java/in/testpress/testpress/ui/ReviewQuestionsFragment.java
When initiating the pager variable, the extended class pager variable
only initializing & not the pager in PagedItemFragment. So, the usages
of that variable always giving null. Now the pager variable in extended
class is removed as it is need not. So, the PagedItemFragment pager is
initializing directly.
> Fix bug in pagination

- app/src/main/java/in/testpress/testpress/core/PostCategoryPager.java
- app/src/main/java/in/testpress/testpress/ui/PostsListFragment.java
Sometimes pager which loads older posts is initialized with
TestpressService, before refreshPager initializes the TestpressService
with auth-token. Therefore auth-token is missing in the API calls which
load the older posts.
This is fixed by getting the TestpressService in all the occurrences
using the getTestpressService method which initializes the
TestpressService with auth-token for the first time & returns the same
instance afterwards.
> Load post categories using pagination and Fix authorization bug

- app/src/main/java/in/testpress/testpress/TestpressModule.java
- app/src/main/java/in/testpress/testpress/TestpressServiceProvider.java
- app/src/main/java/in/testpress/testpress/core/AuthenticationService.java
- app/src/main/java/in/testpress/testpress/core/DeviceService.java
- app/src/main/java/in/testpress/testpress/core/DocumentsService.java
- app/src/main/java/in/testpress/testpress/core/PostService.java
- app/src/main/java/in/testpress/testpress/core/ProductService.java
- app/src/main/java/in/testpress/testpress/core/TestpressService.java
- app/src/main/java/in/testpress/testpress/ui/PostActivity.java
- Authorization header is not sending in the redirecting network
requests. This is fixed by adding authorization header through
OkHttpClient network interceptor.
- Post detail url needs the short_link, which is parsed from the
shortWebUrl by removing the base url. It is now parsed independent of
base url.
> Add authorization header through OkHttpClient network interceptor

- app/src/main/java/in/testpress/testpress/authenticator/RegisterActivity.java
To prevent multiple account creation disabled the register button &
made the progress dialog non-cancelable.
> Prevent multiple account creation

- app/src/main/java/in/testpress/testpress/authenticator/CodeVerificationActivity.java
- Fixed app crash on registering an account by using the automatic mobile number verification method.
- During registering by automatic mobile number verification method. Testpress SDK was not getting initialized.
> Solve app crash issue while registering by phone number

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/in/testpress/testpress/authenticator/CodeVerificationActivity.java
- app/src/main/java/in/testpress/testpress/authenticator/RegisterActivity.java
- app/src/main/java/in/testpress/testpress/events/SmsReceivingEvent.java
- Implement automatic SMS verification with the SMS Retriever API.
- Google has restricted the permission to read SMS for OTP verification.
> Remove sms permission for registration.

- app/build.gradle
- app/src/main/java/in/testpress/testpress/core/Constants.java
- app/src/main/java/in/testpress/testpress/core/TestpressService.java
- app/src/main/java/in/testpress/testpress/models/CheckPermission.java
- app/src/main/java/in/testpress/testpress/network/CheckPermissionService.java
- app/src/main/java/in/testpress/testpress/ui/MainActivity.java
- Added checking condition for force data if the user is authenticated. Every time the user will interact with MainActivity. Codes will check for the institute force setting. If it's true it will ping the API to check is data is collected for the user. If not so it will hide all the UI and will ping sso_url and open the web view to fill the values.
- If the user tries to press the back button, it does all the above process in onResume function. Will again redirect to web view if it didn't find user has filed all the values.
- If some error occurs during pinging the CHECK_PERMISSION_URL or SSO URL. It will hide all the UI and will ask to again refresh the page.
- We have added the feature force data in the web. But still, we were not for
> Force user data in android.

- app/src/main/java/in/testpress/testpress/ui/MainMenuFragment.java
- Excluded about us menu from authentication checking in the dashboard. Not it will be shown without authentication.
- About us do not require authentication to get values. It not user dependent.
- Number of Test Cases - 0
> Exclude about us menu from authentication checking in the dashboard.

- app/src/main/java/in/testpress/testpress/authenticator/LoginActivity.java
- Display client error messages occur while logging, in a pop-up window.
- Earlier we use to show the only invalid `username and password` message for any client error.
- Number of Test Cases - N/A
> Display client error message while logging

- .travis.yml
- Increase Android SDK version to 28 for Travis.
-  Travis was failing after increasing the target SDK to 28
- Number of Test Cases - N/A
> Fix failing travis after increasing the target android version to 28

- app/src/main/java/in/testpress/testpress/ui/TestpressFragmentActivity.java
- Added intent flags to open only one instance of UserDevicesActivity, even if startActivity is called multiple times.
- If the parallel restriction is turned on, then this activity will get called multiple times for multiple requests which will spam the back stack.
> Open only one instance of UserDevicesActivity

- app/src/main/java/in/testpress/testpress/core/TestpressService.java
- app/src/main/java/in/testpress/testpress/ui/MainActivity.java
- Send package_name in check update API
- With this backend can know the package_name from which requests are coming.
- This is useful in case of migration of app from one package name to another
> Send package_name in check update API

- app/src/main/java/in/testpress/testpress/ui/MainActivity.java
- app/src/main/java/in/testpress/testpress/ui/utils/EasterEggUtils.java
- app/src/main/res/layout/main_activity.xml
- Added easter egg to enable screenshot
- When the app is closed and reopened again screenshot status will be default again
- Long press on the version number in the navigation drawer (press until you see toast message)
- Next login press on the right end of rate us button in the navigation drawer (press until you see toast message)
> Add easter egg to enable screenshot

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/in/testpress/testpress/ui/MainActivity.java
- app/src/main/java/in/testpress/testpress/ui/SplashScreenActivity.java
- app/src/main/java/in/testpress/testpress/util/Strings.java
- Specified absolute version for branch dependency
- Moved branch integration code from MainActivity to SplashScreenActivity as SplashScreenActivity is the first activity that will be executed when the app is opened.
- Added share.elixirapp.co URL for deep link
- When Branch is initialized, it will check whether it has a deep link URL. If it has then the app will be directed to the deep link and cancel the splash screen timeout callback
- If the branch do not have a deep link then Splash screen timeout will get over and normal flow will be continued.
> Add branch deeplinking

- app/src/main/java/in/testpress/testpress/ui/fragments/DashboardFragment.java
- If network error(when the app is offline) occurs, dashboard data stored in shared preferences is used.
- Number of Test Cases - NA
> Fix Dashboard not displayed in offline

- app/src/main/java/in/testpress/testpress/ui/SplashScreenActivity.java
- app/src/main/java/in/testpress/testpress/ui/adapters/OffersCarouselAdapter.java
- app/src/main/java/in/testpress/testpress/ui/utils/DeeplinkHandler.java
- We have a class DeepLinkHandler which will handle deep links
- Problem is we are using the deep link handler for 2 cases.
1. When a user clicks link outside from app
2. When user click some link inside the app
- Right now for both cases it is doing same thing (simply opens the app)
- For 1, if link is not recognized then it should open the app and show the main screen
- For 2, if link is not recognized then it should open link in the browser
> Fix deeplink not working bug

- app/src/main/java/in/testpress/testpress/ui/TestpressFragmentActivity.java
- When viewing activity opened from deeplink if back button is pressed, it should go back to main activity instead of closing app.
> Go to home on post opened from deeplink

- app/src/main/java/in/testpress/testpress/ui/adapters/CourseCarouselAdapter.java
- If exams count or notes count or videos count is 0, then it should be hidden
> Hide contents count which is 0 in course carousel

- app/src/main/java/in/testpress/testpress/repository/RegisterRepository.kt
Since the exception is handled in the onException function, the catch block is unnecessary.
> Remove Redundant try catch

- app/src/main/java/in/testpress/testpress/TestpressServiceProvider.java
- Removed the method call which will delete the db data while logout
> Fix: Downloaded videos should not get deleted when logged out

- app/src/main/java/in/testpress/testpress/util/PreferenceManager.java
To clear the data already stored in the Dashboard shared Pref needs to be deleted. Hence the Shared Pref name is renamed
> Rename Dashboard Preference

- app/src/main/java/in/testpress/testpress/ui/utils/HandleMainMenu.java
- App link was not present in the share option. Previously, there was a check if the appLink from Institute settings is null. Now added another check if the string was empty. If both condition satisfies, the link from settings will be shared, or the link with default package name will be shared.
> Fix app link is not present in share option

- app/src/main/res/layout/content_carousel_item.xml
- app/src/main/res/layout/course_carousel_item.xml
- Change image scale type from `centerCrop` to `centerInside`
- In some cases, the thumbnail is getting cropped and full view is not visible. So made the change to display the complete image.
> Fix image get cropped in dashboard

- fastlane/actions/get_app_config.rb
- This issue is we haven't constructed the URL correctly in Fastlane, this causes the `Not an HTTP URI` error while fetching. that is fixed in this commit.
> fix: Fix the bug while fetching app config through API

- fastlane/Fastfile
- The issue is we replaced splash screen `1280 * 720` with `2048 * 1536`  and `2048 * 1536` with `1280 * 720`, and this is fixed in this commit.
> fix: Fix incorrect image replacement in fastlane automation

- fastlane/actions/modify_config_json_file.rb
- The issue we haven't replaced the version code and version name in the config JSON with the institute version. this is fixed in this commit.
> fix: Fix version number and name not updated in app deployment

- .github/workflows/build_app.yml
- Removed ref input from build_app Github action, because by default GitHub action asks for a branch or tag to run on, so it's redundant to have a ref input field in the workflow.
> fix: Remove ref input from build_app Github action

- app/src/main/java/in/testpress/testpress/TestpressServiceProvider.java
- We are setting the Facebook app id as an empty string in the config json if the institute doesn't have one while customizing using Fastlane, because of this, the app crashes when the user tries to logout from the app,
- Because FacebookSDK raises an exception if we initialize it with an empty string as Facebook application id, this unhandled Exception causing App crash.
- This is fixed by only initializing the FacebookSDK if the institute has a Facebook app id.
> fix: Fix app crash while logout if app dont have facebook app id

- app/build.gradle
- While running the GitHub action for app build, we are getting this issue `No version of NDK matched the requested version 21.0.6113669. Versions available locally: 21.4.7075529, 23.2.8568313, 24.0.8215888` that is fixed in this commit by using NDK version 21.4.
> fix: Update NDK version to 21.4 for gradle build

- app/build.gradle
- Updated these test dependencies in order to prevent build errors while testing the app in the emulator with API version 31.
> fix: Update test dependencies

- app/src/main/java/in/testpress/testpress/authenticator/LoginActivityV2.kt
- After updating the google auth dependencies, GoogleSignInResult getId and getIdToken methods return optional null, which causes Kotlin compile time error because accessed those values without null check. 
- Which was fixed in the commit by accessing the return value after the null check.
> fix: Fix kotlin compile time error which caused by 0a19197

- app/build.gradle
- app/src/main/java/in/testpress/testpress/TestpressServiceProvider.java
- Added new Testpress SDK version 1.4.69
- set app_name in institute settings
- Issue is watermark in Quiz review Fragment is displayed as "Testpress SDK" instead of app name
- Number of Test Cases - Nil
> fix: Display app_name watermark from Institute settings in QuizReviewFragnment

- app/src/main/java/in/testpress/testpress/ui/MainMenuFragment.java
- app/src/main/java/in/testpress/testpress/ui/utils/HandleMainMenu.java
-  Replace bookmark import in ManiMenuFragment and HandleMainmenu
- Bookmark functionality moved from exam library to course library
- Number of Test Cases - Nil
> fix: Replace bookmark import statement

- app/src/main/java/in/testpress/testpress/ui/utils/DeeplinkHandler.java
-  Added validation for selected link to open ExamListViewActivity
-  Open MainActivity for other links
-  App crash while opening the app using the link
- Number of Test Cases -  Nil
> fix: App crash while opening via shared link

- app/build.gradle
- We are getting this error at runtime `More than one file was found with OS independent path 'lib/arm64-v8a/libc++_shared.so'.` in the mergeReleaseNativeLibs Gradle task, this was fixed in this commit by picking the first file while packing.
> fix: Fix mergeReleaseNativeLibs gradle task failure in github action

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/in/testpress/testpress/ui/WebViewActivity.java
-  Added validation to institute URL while using webview
-  Added auto-generation of white labeled URL in Gradle file
-  Added deep link URL in Android Manifest for the custom domain to open the app
-  user is able to open other links in the institute app
> fix:able to open non institute links in app webview

- fastlane/Fastfile
- Because these apps must be released from their customized branch, not from the master.
> fix: Exclude brilliantpala and veranda apps while releasing update for all

- app/src/main/java/in/testpress/testpress/ui/fragments/PhoneAuthenticationFragment.kt
- app/src/main/java/in/testpress/testpress/ui/fragments/UsernameAuthentication.kt
- app/src/main/res/layout-h800dp/phone_login_layout.xml
- app/src/main/res/layout-hdpi/phone_login_layout.xml
- app/src/main/res/layout-xhdpi/phone_login_layout.xml
- app/src/main/res/layout/phone_login_layout.xml
- Remove Create account button in the OTP login screen
- open webView only for user registration with custom fields
- open the registration screen for default user registation
- WebView opens when the user tries to register, Webview is only for user registration with custom fields
> fix: Allow WebView for user registration with custom fields

- app/src/main/java/in/testpress/testpress/util/NotificationHelper.java
- Added expandable notifications to show the long content
- If the notification content long we can't able to see the full content
> fix: Add expandable notifications

- app/src/main/java/in/testpress/testpress/ui/MainActivity.java
- Previously users could see public posts if user not authenticated (allow_anonymous_user = true)
- At that time we sync offline video data, If offline video data syncing needs testpressSession
- TestpressSession will create after the user login
- This is the reason for this issue
- Now we moved offline video data syncing after UserAuthenticated
> fix: App crash after its open

- app/src/main/java/in/testpress/testpress/ui/fragments/OTPVerificationFragment.kt
- app/src/main/res/layout-h800dp/otp_verification_layout.xml
- app/src/main/res/layout-hdpi/otp_verification_layout.xml
- app/src/main/res/layout-xhdpi/otp_verification_layout.xml
- app/src/main/res/layout/otp_verification_layout.xml
- added action listener for otpFiled
- Add hide soft keyboard
- This issue is already fixed in this commit https://github.com/testpress/android/commit/9e01ea1c0c948c92735f2c1ed5b4676c4c6bcc4d
-  We missed this otp verification screen
> fix: Not able hide soft keyboard in otp verification screen

- app/src/main/java/in/testpress/testpress/ui/ProfileDetailsActivity.java
- app/src/main/res/layout/profile_detail_layout.xml
- As the ProfileDetails API no longer provides the address value, we are disabling the use of address by commenting out the corresponding code for setting the address and the layout in the view.
> fix: Remove usage of Address in profile detail view

- app/src/main/AndroidManifest.xml
- app/src/main/res/values/styles.xml
- We use the same theme for all activities with the default text color white.
- This is applicable for Date pickers also but here Date picker's background is white and the text is also white so the text is not visible.
- In this commit, we created a separate theme for webview activity with the default text color.
> fix: Dates not visible in Date picker

- app/build.gradle
- app/src/main/assets/config.json
- app/src/main/java/in/testpress/testpress/TestpressServiceProvider.java
- We recently integrated Razorpay in SDK in commit
https://github.com/testpress/android-sdk/commit/56a3dc16b24a1f67c09c23533374bfafde358c38.
- This commit exposes `current_payment_app` required in the
integration to decide which payment gateway to use.
- 
- 
- Number of Test Cases -
> fix: Expose current payment app in app config

- app/src/main/res/layout/offers_carousel_item.xml
- Recently we enforced the banner size as 1500x600 for the new landing page on the web.
- in this commit, the banner ad size is changed to 375x150 which is equivalent to 1500x600.
> fix: Change Banner ad resolution to 1500x600 in Dashboard

- app/src/main/java/in/testpress/testpress/ui/fragments/OTPVerificationFragment.kt
- We provided fragment object to life cycle observe
- In this commit, We passed ViewLifecycleOwner object to life cycle observe because observe required ViewLifecycleOwner object
> refactor: ViewLifecycleOwner object in OTPVerificationFragment

- app/src/main/java/in/testpress/testpress/TestpressServiceProvider.java
- app/src/main/java/in/testpress/testpress/models/InstituteSettings.java
- app/src/main/java/in/testpress/testpress/models/InstituteSettingsDao.java
- testpressdaogenerator/src/main/java/in/testpress/testpress/TestpressDaoGenerator.java
- Previously we added the currentPaymentApp field in config.json. This is not the right way because every time we need to release an update if we change the payment App.
- In this commit, Added the enableCustomTest field in the InstituteSettings Model.
- Set the enableCustomTest field in SDK InstituteSettings.
> fix: Add currentPaymentApp field in InstituteSettings Model

- app/src/main/AndroidManifest.xml
- app/src/main/java/in/testpress/testpress/ui/MainActivity.java
- Android Version 13 and higher require runtime notifications to use notification functionality.
- In this commit, we ask for notification permission after the user logs in.
> fix: Add ask notification permission for android version 13 and above

- app/src/main/java/in/testpress/testpress/ui/MainActivity.java
- In this commit d3e8cc5 we add Ask Notification permission to the user in MainActivity so that the notification permission popup launches before the LoginActivity shows
- Now in this commit, we ask for notification permission to the user after the user made a successful login.
> fix: Ask Notification permission after user login

- app/src/main/res/menu/main_menu.xml
- In this commit, we initially hide the post and student report buttons in the NavigationDrawer for anonymous users. These features require user login, and after the user logs in, we validate their access based on the institution's settings.
> fix: Hide post and student report button before user login

- app/build.gradle
- In this commit, we're increasing the minimum SDK version to 23. This change is necessary because we're incorporating the Zoom SDK into our app, and for this release, we need to update the Zoom SDK version to 5.13.5.11583. It's important to note that in this release, the minimum SDK version required by the Zoom SDK has been raised to 23, so we are aligning our app's requirements accordingly.
> fix: Update Android minimum SDK version to 23

- app/src/main/java/in/testpress/testpress/ui/MainActivity.java
- We've just integrated a custom store WebView into the Android SDK project, which means we now have to implement stack-back functionality for this custom WebView within the MainActivity of our app.
> fix: Handled BackPress for custom store webview in MainActivity

- app/build.gradle
- fastlane/actions/modify_config_json_file.rb
- In our Android app, we save the app_name in an XML file. However, Android XML resource files do not support single quotes.
- In this commit, we sanitize the `app_name` in before generating the `config.json` file
> fix: App not build if app name contains single quotes

- app/build.gradle
- app/src/main/java/in/testpress/testpress/ui/fragments/DiscussionFragmentv2.kt
- In this commit, we used Testpress android SDK version `1.4.127` to `1.4.128`.
- We removed the ExperimentalPagingApi annotation in the `DiscussionFragment` within the Android SDK project. Since `DiscussionFragmentv2` is a subclass of `DiscussionFragment`, we are applying the same modification to it.
> fix: Use Testpress SDK version 1.4.128

- app/src/main/java/in/testpress/testpress/ui/MainActivity.java
- From now on, if the user is not logged in, we call the InstituteSettingsAPI without an authentication token. If the user is already logged in, we call the InstituteSettingsAPI with an authentication token because, from now onwards, the institute is personalized to the user.
> enhancement: Add InstituteSettingsAPI call with user authentication.

- app/build.gradle
- app/src/main/java/in/testpress/testpress/ui/DoubtsActivity.kt
- `kotlin-android-extensions` is depreciated so we are migrating to `viewbinging`  [Docs](https://goo.gle/kotlin-android-extensions-deprecation)
- In this commit we replaced `viewBinding` instead of `kotlin-android-extensions` in DoubtsActivity
> enhancement: Use `viewBinding` instead of `kotlin-android-extensions` in DoubtsActivity

- app/build.gradle
- app/src/main/java/in/testpress/testpress/ui/fragments/RegistrationBaseFragment.kt
- In this commit, we replaced `viewBinding` instead of `kotlin-android-extensions` in RegistrationBaseFragment
> enhancement: Use `viewBinding` instead of `kotlin-android-extensions` in RegistrationBaseFragment

- app/src/main/java/in/testpress/testpress/ui/fragments/AutoLoginFragment.kt
- In this commit, we replaced `viewBinding` instead of `kotlin-android-extensions` in AutoLoginFragment
> enhancement: Use `viewBinding` instead of `kotlin-android-extensions` in AutoLoginFragment

- app/src/main/java/in/testpress/testpress/ui/fragments/EmailVerificationFragment.kt
- app/src/main/res/layout/register_activity.xml
- In this commit, we replaced `viewBinding` instead of `kotlin-android-extensions` in EmailVerificationFragment
> enhancement: Use `viewBinding` instead of `kotlin-android-extensions` in EmailVerificationFragment

- app/src/main/java/in/testpress/testpress/ui/fragments/OTPVerificationFragment.kt
- In this commit, we replaced `viewBinding` instead of `kotlin-android-extensions` in OTPVerificationFragment
> enhancement: Use `viewBinding` instead of `kotlin-android-extensions` in OTPVerificationFragment

- app/src/main/java/in/testpress/testpress/ui/fragments/PhoneAuthenticationFragment.kt
- In this commit, we replaced `viewBinding` instead of `kotlin-android-extensions` in PhoneAuthenticationFragment
> enhancement: Use `viewBinding` instead of `kotlin-android-extensions` in PhoneAuthenticationFragment

- app/src/main/java/in/testpress/testpress/ui/fragments/PhoneVerificationFragment.kt
- In this commit, we replaced `viewBinding` instead of `kotlin-android-extensions` in PhoneVerificationFragment
> enhancement: Use `viewBinding` instead of `kotlin-android-extensions` in PhoneVerificationFragment

- app/build.gradle
- build.gradle
- Updated Kotlin version from `1.7.0` to `1.8.0`.
- Removed `kotlin-android-extensions` as it's deprecated in Kotlin `1.8.0`. See [Docs](https://android-developers.googleblog.com/2022/02/discontinuing-kotlin-synthetics-for-views.html) for more details.
> enhancement: Update Kotlin version to 1.8.0

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- Updated Android Gradle Plugin version from `7.0.4` to `7.2.2`.
- Updated Gradle version from `7.0.2` to `7.3.3`.
- Updated corresponding dependencies. See [Docs](https://developer.android.com/build/releases/past-releases/agp-7-2-0-release-notes) for more details.
> enhancement: Update Android Gradle Plugin version to `7.2.2`

- app/src/main/java/in/testpress/testpress/ui/utils/HandleMainMenu.java
- The reason for the back stack not working is due to the usage of CustomTestGenerationActivity to display the Discussion webview. By replacing it with WebViewWithSSOActivity, we can resolve this issue.
> fix: Back stack not working on Discussion activity 

- app/src/main/java/in/testpress/testpress/ui/MainActivity.java
- In this commit, we are adding a new Easter egg to enable screenshots. Additionally, we removed the old Easter egg because when the branding field is set to true in the institute settings, we were not able to enable screenshots.
> enhancement: Add new Easter egg to enable screenshots

- app/src/main/java/in/testpress/testpress/TestpressServiceProvider.java
- app/src/main/java/in/testpress/testpress/ui/fragments/OTPVerificationFragment.kt
- In this commit, we set `androidSentryDns` in InstituteSettings of the SDK.
- To ensure Sentry is not initialized during the OTP login process, we initialize Sentry after the OTP login success.
> enhancement: Set androidSentryDns in InstituteSettings of sdk

- app/build.gradle
- app/src/main/java/in/testpress/testpress/ui/MainActivity.java
- In this commit, we updated the Sentry Android dependency to `6.4.2`.
> enhancement: Update Sentry android dependencies version to `6.4.2`

- app/src/main/java/in/testpress/testpress/TestpressServiceProvider.java
- app/src/main/java/in/testpress/testpress/authenticator/CodeVerificationActivity.java
- app/src/main/java/in/testpress/testpress/authenticator/LoginActivity.java
- app/src/main/java/in/testpress/testpress/authenticator/LoginActivityV2.kt
- app/src/main/java/in/testpress/testpress/ui/fragments/OTPVerificationFragment.kt
- app/src/main/java/in/testpress/testpress/ui/fragments/UsernameAuthentication.kt
- app/src/main/java/in/testpress/testpress/viewmodel/AutoLoginViewModel.kt
- In this commit, we set `androidSentryDns` in InstituteSettings of the SDK.
- To ensure Sentry is not initialized during the OTP login process, we initialize Sentry after the OTP login success.
> fix: Set androidSentryDns in InstituteSettings of sdk

- app/src/main/java/in/testpress/testpress/ui/utils/EasterEggUtils.java
- Once the user enables screenshots using the easter egg, we were updating the SDK institute settings but not the app institute settings.
- In this commit, we are updating the app institute settings once the user enables screenshots using the easter egg.
- This easter egg will work until the user reopens or relaunches the app.
> fix: Screenshots  easter egg not working properly

- app/src/main/java/in/testpress/testpress/ui/MainActivity.java
- app/src/main/res/menu/main_menu.xml
- Handled the bookmark option based on institute settings.
- Applied the same logic for the discussion option to ensure correct visibility according to portal configuration.
> fix: Bookmarks and Discussion button showing in sidebar even if disabled in the portal

- app/src/main/AndroidManifest.xml
- Deeplink was not working on Android 12 and higher. In this commit, we added the `autoVerify` attribute to `true` in the AndroidManifest to resolve the issue.
> fix: Institute URL not opening in the app on Android 12 and higher

- app/build.gradle
- In this commit, we updated Google Play Services dependencies from version `20.2.0` to `20.7.0`.
>  fix: Update google play services dependencies

- app/src/main/java/in/testpress/testpress/ui/MainActivity.java
- Previously, the login screen would open multiple times if the "Enforce Student Data" option was enabled in institute settings. This occurred because the enforcement check was performed before user authentication.
- In this commit, we have updated the logic to check the "Enforce Student Data" setting only after the user has been authenticated. This change resolves the issue of multiple login screens appearing.
> fix: Prevent multiple login screens when Enforce Student Data is enabled

- app/build.gradle
- In this commit, we update the country code picker package version `2.4.2` to `2.7.0`.
> enhancement: Update country code picker dependencies to `2.7.0`

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- Updated Android Gradle Plugin version from `7.2.2` to `7.4.2`.
- Updated Gradle version from `7.3.3` to `7.5`.
- Updated corresponding dependencies. See [Docs](https://developer.android.com/build/releases/past-releases/agp-7-4-0-release-notes) for more details.
> enhancement: Update Android Gradle Plugin version to `7.4.2`

- app/src/main/AndroidManifest.xml
- The following permission `android.permission.FOREGROUND_SERVICE_PHONE_CALL` was requested by the Zoom SDK.
- Since our app does not utilize this permission, it has been explicitly removed to avoid unnecessary permission requests.
> fix: Removed unnecessary permission

- .github/workflows/release_update.yml
- fastlane/Fastfile
- In this commit, we added the option to upload the app file to the Google Play Console and create a release draft without submitting it for review.
- Previously, running the release update would automatically submit the app for review. In some cases, we need to delay the submission, so we added this option to allow for creating a draft release without immediate submission.
> enhancement: Create draft release in Play Console via GitHub Action

- gradle.properties
- GitHub release action failed due to `OutOfMemoryError`. Increasing the Gradle daemon heap size is expected to resolve this issue.
> fix: Increase Gradle daemon heap size

- app/build.gradle
- app/src/main/java/in/testpress/testpress/ui/MainActivity.java
- app/src/main/res/drawable/outline_info_24.xml
- app/src/main/res/layout/main_activity.xml
- app/src/main/res/menu/main_menu.xml
- Adding more options to the navigation caused the version view to overlap with menu options. In this commit, we moved the version to be one of the menu options.
- The existing easter egg functionality remains unchanged and continues to work with the new version option placement.
> fix: App version view overlaps with menu options

- app/src/main/java/in/testpress/testpress/ui/MainActivity.java
- app/src/main/java/in/testpress/testpress/ui/utils/HandleMainMenu.java
- app/src/main/java/in/testpress/testpress/util/AppChecker.kt
- app/src/main/res/drawable/outline_smart_display_24.xml
- app/src/main/res/menu/main_menu.xml
- This commit adds three custom options to the navigation slider: Recorded Lessons, Mocks, and E-Books.
- These options are exclusively visible in the Catking app. When a user selects any of these options, the respective Catking external URL opens in the webview.
> enhancement: Add Catking custom options to Navigation Slider

- app/build.gradle
- app/src/main/java/in/testpress/testpress/ui/MainActivity.java
- Previously, after user authentication, we only requested notification permission. Now, we also request storage permission immediately after login because it is needed in more than five places throughout the app.
- Requesting storage permission at this point is crucial as it ensures seamless functionality across various features that rely on storage access.
- Upgraded Testpress SDK version from `1.4.164` to `1.4.165`.
> fix: Request Storage permission after user login

- app/src/main/java/in/testpress/testpress/ui/utils/AutoDetectOTP.kt
- Previously, the broadcast receiver was registered without considering the Android version. Now, we conditionally use `RECEIVER_EXPORTED` for Android 13 and above to comply with new security requirements. This change prevents `SecurityException` and ensures proper receiver registration based on the Android version. For more details, refer to [Android Developer Documentation](https://developer.android.com/develop/background-work/background-tasks/broadcasts#context-registered-receivers).
> fix: Not able to navigate to OTPVerificationFragment after entering the mobile number

- .github/workflows/release_update.yml
- In commit 7b720b2, we added an option to upload the app file to the Google Play Console and create a release draft without submitting it for review.
- The `release_option` field was set as required, but its value was not being received from the Android App config form, causing the action to fail.
- In this commit, we set `release_option` as a non-required field with the default value set to `completed`.
> fix: Unable to release update from Android App config form

- .github/workflows/release_update.yml
- Release actions were failing due to the deprecated `actions/upload-artifact@v2`.
- In this commit, we updated the action to `actions/upload-artifact@v4`, which resolves the issue.
> fix: Release Actions are failing

- .github/workflows/build_app.yml
- Build actions were failing due to the deprecated `actions/upload-artifact@v2`.
- In this commit, we updated the action to `actions/upload-artifact@v4`, which resolves the issue.
> fix: Build Actions are failing

- app/src/main/java/in/testpress/testpress/authenticator/CodeVerificationActivity.java
- App crashes on Android 13 (API level 33) and higher during SMS verification. The issue was caused by the `registerReceiver` method, which now requires the `RECEIVER_EXPORTED` flag on Android 13 and above. 
- Updated the `registerReceiver` call to use the RECEIVER_EXPORTED flag for devices running Android 13 (Tiramisu) or higher.
- For more details, refer to [Android Developer Documentation](https://developer.android.com/develop/background-work/background-tasks/broadcasts#context-registered-receivers).
> fix: App crash on Android 13+ during SMS verification

- app/src/main/java/in/testpress/testpress/ui/utils/DeeplinkHandler.java
- Users can only reset their passwords through the browser. However, when users click the password reset URL on an Android mobile device, the app opens instead, preventing them from resetting their password.
- In this commit, we ensure that when users click the password reset URL, they are redirected to the browser to facilitate the password reset process.
> fix: Deep Link Handling for Password Reset

- app/src/main/java/in/testpress/testpress/ui/adapters/CourseCarouselAdapter.java
- app/src/main/res/layout/course_carousel_item.xml
- app/src/main/res/values/strings.xml
- Previously, we displayed exam, video, and notes counts in the product list view on the dashboard. This approach was inconsistent as there are four additional content types.
- This commit replaces the specific counts with a unified chapter and content count to maintain consistency across the dashboard and store screens.
> refactor: Replace exam, video, and notes count with chapter and content count in dashboard

- app/build.gradle
- app/src/main/java/in/testpress/testpress/util/CommonUtils.java
- Updated `firebase-core` to `21.1.1` and `firebase-messaging` to `24.1.0`.
- Replaced deprecated `FirebaseInstanceId` with` FirebaseMessaging.getToken()`.
- Ensures compatibility with the latest Firebase SDK and removes deprecated API usage.
> fix: Update Firebase dependencies

- app/build.gradle
- app/src/main/java/in/testpress/testpress/ui/MainActivity.java
- app/src/main/java/in/testpress/testpress/util/SalesforceSdkInitializer.java
- build.gradle
- This PR integrates the Salesforce Marketing Cloud SDK for push notifications.
- Added `marketingcloudsdk` dependency in `build.gradle`.
- Implemented `SalesforceSdkInitializer` to configure and initialize the SDK in `MainActivity`.
- Added logic to handle notification permission and enable push notifications upon grant.
> feat: Integrate Salesforce Marketing Cloud SDK for Enhanced Push Notifications

- app/src/main/AndroidManifest.xml
- app/src/main/java/in/testpress/testpress/TestpressModule.java
- app/src/main/java/in/testpress/testpress/ui/EnforceDataActivity.kt
- app/src/main/java/in/testpress/testpress/ui/MainActivity.java
- Previously, the `WebViewActivity` lacked a JavaScript interface callback, causing the WebView activity to remain open after data submission.
- Added `EnforceDataActivity` to handle data submission and close the activity upon successful submission.
- Removed the old implementation for enforcing data.
> fix: Unable to return to dashboard after submitting Enforce Data form

- app/src/main/java/in/testpress/testpress/ui/EnforceDataActivity.kt
- This PR fixes an issue in `EnforceDataActivity` where the overridden `onCreateOptionsMenu` method did not accept a nullable Menu. This caused issues when passing null values, potentially leading to build failures. Ref - [Docs](https://www.jot.fm/issues/issue_2005_03/column2/#:~:text=An%20inheritance%20conflict%20arises%20when,accidental%20and%20recombinant%20inheritance%20conflicts.)
> fix: Resolve Inheritance Conflict Resolution Error

- .github/workflows/build_app.yml
- .github/workflows/generate_debug_apk.yml
- .github/workflows/release_update.yml
- Updated GitHub Actions workflows to use JDK 17 with the Temurin distribution. The change resolves build failures caused by incompatibility between the Android SDK's command-line tools (requiring JDK 17) and the previously configured JDK 11.
> fix: Resolve GitHub Actions build failures

- app/src/main/java/in/testpress/testpress/ui/fragments/DashboardFragment.java
- This PR resolves an issue where the dashboard API was being called multiple times during the initialization of DashboardFragment.
- The API was being called three times: once in onCreate() and twice in onResume().
- The redundant calls in onResume() were unnecessary and caused inefficiencies.
- Removed the onResume() override where refresh() was being called.
- This ensures the API is only called during initialization or as explicitly required, preventing duplicate calls.
> fix: Prevent redundant API calls in DashboardFragment

- app/src/main/java/in/testpress/testpress/ui/MainActivity.java
- app/src/main/java/in/testpress/testpress/ui/ProfileDetailsActivity.java
- app/src/main/java/in/testpress/testpress/ui/utils/DeeplinkHandler.java
- app/src/main/java/in/testpress/testpress/ui/utils/HandleMainMenu.java
- Previously, webviews for privacy policy, enforce data form, discussions, etc., were always opened using our own domain (BASE_URL). However, some institutions use custom domains, and these webviews were not working correctly for them.
- Updated the code to use WHITE_LABELED_HOST_URL instead of BASE_URL for all relevant webviews.
- If a custom domain is not available, the default domain (our domain) will be used as specified in the WHITE_LABELED_HOST_URL field.
> fix: Use WHITE_LABELED_HOST_URL for webviews to support custom domains 

- app/src/main/AndroidManifest.xml
- The app was requesting storage permissions on Android 10 and higher, where the permission is no longer necessary.
- This permission was used for features allowing users to download attachments and review PDF files directly to the external download directory. However, starting with Android 10, the permission is no longer required.
- The permission check was updated to restrict storage access to devices with SDK <= P (Android 9), and the manifest was revised to request the permission only for devices with SDK <= 28. [Reference](https://developer.android.com/reference/android/app/DownloadManager.Request#setDestinationInExternalPublicDir(java.lang.String,%20java.lang.String))
> fix: Remove unnecessary storage permission for Android 10 and above

- app/src/main/java/in/testpress/testpress/ui/utils/HandleMainMenu.java
- Previously, webviews for custom Caking External URL, were always opened using our own domain (BASE_URL). However, catking uses custom domains, and these webviews were not working correctly for them.
- Updated the code to use WHITE_LABELED_HOST_URL instead of BASE_URL for all relevant webviews.
- If a custom domain is not available, the default domain (our domain) will be used as specified in the WHITE_LABELED_HOST_URL field.
> fix: Use WHITE_LABELED_HOST_URL for webviews to support custom domains

- app/src/main/java/in/testpress/testpress/TestpressServiceProvider.java
- app/src/main/java/in/testpress/testpress/authenticator/CodeVerificationActivity.java
- app/src/main/java/in/testpress/testpress/authenticator/LoginActivity.java
- app/src/main/java/in/testpress/testpress/authenticator/LoginActivityV2.kt
- app/src/main/java/in/testpress/testpress/ui/PostsListFragment.java
- app/src/main/java/in/testpress/testpress/ui/fragments/UsernameAuthentication.kt
- app/src/main/java/in/testpress/testpress/viewmodel/AutoLoginViewModel.kt
- The white-labeled host URL was not being set in the InstituteSettings during various activities (e.g., CodeVerificationActivity, LoginActivity, UsernameAuthentication, etc.), leading to inconsistent configuration.
- The WHITE_LABELED_HOST_URL was not being initialized from BuildConfig in some key areas of the application.
- Added the setWhiteLabeledHostUrl(BuildConfig.WHITE_LABELED_HOST_URL) to ensure the white-labeled host URL is correctly initialized in the InstituteSettings object across multiple activities and view models.
> fix: Add white-labeled host URL in InstituteSettings for consistent configuration

- app/src/main/java/in/testpress/testpress/core/PostService.java
- app/src/main/java/in/testpress/testpress/core/PostsPager.java
- app/src/main/java/in/testpress/testpress/core/TestpressService.java
- app/src/main/java/in/testpress/testpress/ui/PostsListFragment.java
- Previously, when a user refreshed posts, only new posts (based on the last modified date) were fetched, optimizing data retrieval.
- However, if an admin deleted a post, the deleted post remained in the local database since it wasn’t included in the fetch logic.
This caused inconsistencies between the server and local data.
- Removed last modified date filtering from post fetching logic.
- Now, on each refresh, all posts are fetched from the API, local posts are deleted, and the latest posts are stored.
> fix: Resolve pagination issue in running content

- .github/workflows/build_app.yml
- .github/workflows/generate_debug_apk.yml
- .github/workflows/release_update.yml
- GitHub actions were failing due to the deprecated `actions/cache@v2`.
- In this commit, we updated the action to `actions/cache@v3`, which resolves the issue.
> fix: Resolve GitHub Actions failures

- app/src/main/java/in/testpress/testpress/ui/fragments/AutoLoginFragment.kt
- app/src/main/java/in/testpress/testpress/ui/fragments/RegistrationBaseFragment.kt
- app/src/main/java/in/testpress/testpress/viewmodel/RegisterViewModel.kt
- app/src/main/res/layout-xlarge/register_activity.xml
- app/src/main/res/layout/register_activity.xml
- Previously, the country code option was not visible during mobile registration, forcing users to register with a default country code. This update makes the country code picker visible next to the phone number input field, allowing users to select their country code before entering their phone number.
> fix: Enable country code picker in mobile registration

- app/src/main/java/in/testpress/testpress/ui/view_holders/CourseCarouselViewHolder.java
- Added a `See All` button in CourseCarouselViewHolder to allow users to view the full product list.
- The button is now visible whenever a course carousel section is displayed.
- Clicking on 'See All' navigates the user to the Product list view.
> feat: Add See All button to Course Carousel

- app/src/main/java/in/testpress/testpress/authenticator/LoginActivity.java
- Previously, clicking Forgot Password opened `ResetPasswordActivity`.
- However, since Brilliant Pala does not use this functionality, we now display a message in an alert dialog instead.
> fix: Show password reset alert when clicking Forgot Password

- app/src/main/java/in/testpress/testpress/authenticator/LoginActivity.java
- Updated setLoginLabel method to set hints on usernameText and passwordText instead of usernameInputLayout and passwordInputLayout.
- Ensures the correct UI elements display dynamic labels based on institute settings.
- Fixes potential UI inconsistency where the wrong elements were being updated with custom labels.
> fix: Correct hint assignment for username and password fields in LoginActivity

- app/src/main/java/in/testpress/testpress/ui/PostActivity.java
- The legacy discussion implementation triggered API calls every 10 seconds to fetch new comments, leading to unnecessary server load.
- This behavior remained even after the new discussion feature was added, as the old UI code wasn't removed immediately.
- This change removes the outdated comment polling logic and related handlers to clean up unused code.
> refactor: Remove legacy periodic comment sync from PostActivity

- app/build.gradle
- The app was using SDK 34, which may cause compatibility issues with the latest Android versions and Play Store requirements.
- This happened because the project had not been updated to align with the latest Android SDK release.
- Updated both compile and target SDK versions to 35 to ensure compatibility and future-proof the app.
> chore: update compile and target SDK to 35
